depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders do
      resources :line_items
      get :ship, on: :member
    end
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
  

  

  

  

  

end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cema's Tea Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
	<%= form_tag store_path, method: :get, class: 'locale' do %>
		<%= select_tag 'set_locale', 
			options_for_select(ApplicationController::LANGUAGES, I18n.locale.to_s),
			onchange: 'this.form.submit()' %>
		<%= submit_tag 'submit' %>
		<%= javascript_tag "$('.locale input').hide()" %>
	<% end %>
	  
		<%= image_tag("logo.jpg") %>
		<%= @page_title || t('.title') %>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>	
			<% end %>
			
			<ul>
				<li><a href="/"><%= t('.home') %></a></li>
				<li><a href="/"><%= t('.questions') %></a></li>
				<li><a href="/"><%= t('.news') %></a></li>
				<li><a href="/"><%= t('.contact') %></a></li>
			</ul>
			
			<% if session[:user_id] %>
				<ul>
					<li><%= link_to t('.orders'), orders_path %></li>
					<li><%= link_to t('.products'), products_path %></li>
					<li><%= link_to t('.users'), users_path %></li>
					<%= button_to t('.logout'), logout_path, method: :delete %>
				</ul>			
			<% end %>

			<div class="time">
				<%= sanitize(Time.now.strftime("%d.%m.%Y<br/>%H:%M")) %>
			</div>
			<br/>
			<div class="counter">
				<%= t('.counter', count: @session_counter.to_i.ordinalize) %>
			</div>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>