depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders do
      resources :line_items
      get :ship, on: :member
    end
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
  

  

  

  

  

end

depot/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			product = Product.find(product_id)
			current_item = line_items.build(product_id: product.id, price: product.price)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum {|item| item.total_price}
	end
end

depot/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]
  skip_before_filter :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      set_cart
    rescue ActiveRecord::RecordNotFound
      logger.error "Trying to access unexisting cart #{params[:id]}"
      redirect_to store_url, notice: 'Unexisting cart'
    else
      respond_to do |format|
        format.html
        format.json {render json: @cart}
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      # @cart = Cart.find(params[:id])
      @cart = current_cart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

depot/app/helpers/carts_helper.rb
module CartsHelper
end

depot/app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
	<div class="cart_title"><%= t('.title') %></div>

	<table>
		<%= render(cart.line_items) %>

		<tr class="total_line">
			<td colspan="2">Total</td>
			<td class="total_cell">
				<%= number_to_currency(cart.total_price) %>
			</td>
			<td>
				<%= button_to 'X', cart, 
					method: :delete, 
					remote: true, 
					confirm: t('.confirm_delete') %>
			</td>
		</tr>
	</table>
	<%= button_to t('.checkout'), new_order_path, method: :get %>
<% end %>

depot/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depot/app/views/carts/destroy.js.erb
$('#cart').hide('blind',2000);

depot/app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

depot/app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

depot/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

depot/app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<%= render @cart %>