depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders do
      resources :line_items
      get :ship, on: :member
    end
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
  

  

  

  

  

end

depot/app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

depot/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: :create

  # GET /line_items
  # GET /line_items.json
  def index
    if params[:order_id]
      @line_items = Order.find(params[:order_id]).line_items
    else
      @line_items = LineItem.all
    end
    respond_to do |format|
      format.html
      format.json { render json: @line_items }
      format.xml { render xml: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    if params[:line_item]
      params[:line_item][:order_id] = params[:order_id]
      @line_item = LineItem.new(params[:line_item])
    else
      product = Product.find(params[:product_id])
      @line_item = @cart.add_product(product.id)
    end


    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js  { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = current_cart

    if @line_item.quantity <= 1
      if @cart.line_items.size <= 1
        @cart.destroy
      else
        @line_item.destroy
      end
    else
      @line_item.quantity -= 1
      @line_item.save
    end

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js { @current_item = @line_item }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depot/app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
	<tr id="current_item">
<% else %>
	<tr>	
<% end %>

	<td><%= line_item.quantity %> &times; </td>
	<td><%= line_item.product.title %></td>
	<td class="item_price">
		<%= number_to_currency(line_item.total_price) %>
	</td>
	<td>
	<% unless line_item.nil? %>
		<div class="item_controls">
			<%= button_to 'X', line_item, 
				method: :delete, 
				remote: true, 
				confirm: "Delete #{line_item.product.title} from cart?" %>
		</div>
	<% end %>
		
	</td>
</tr>

depot/app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", 
			line_item.quantity,
			truncate(line_item.product.title, length: 50)) %>

depot/app/views/line_items/create.js.erb
$('#notice').hide('blind', 1000);

$('#cart').html("<%= j render @cart %>");

<% if (@cart.line_items.size == 1) && (@cart.line_items.first.quantity == 1) %>
	$('#cart').hide();
	$('#cart').show('blind', 2000);
<% end %>


$('#current_item').css({'background-color':'#88ff88'}).
	animate({'background-color':'#114411'}, 1000);

depot/app/views/line_items/destroy.js.erb
<% if @cart && @cart.line_items.size != 0 %>
	$('#cart').html("<%= j render @cart %>");
<% else %>
	$('#cart').hide('blind',2000);
<% end %>

$('#current_item').css({'background-color':'#88ff88'}).
	animate({'background-color':'#114411'}, 1000);

depot/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

depot/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>